### ISSUE TITLE
New exe to uninstall edge plan?

### ISSUE THREAD

**Issue by seba2282** [ionuttbara/edge-remover#23]
How in topic. New exe to uninstall edge will be? Without that bonuses with add chrome. Only how was earlier. Exe removed edge he putted rules to don't come with update to reinstall that

Best Regards

**Comment by ionuttbara** [comment]
1. I don't launch any EXEs for Edge Remover and OneDrive Remover because i want to move that in simple scripts. (its not need reboot, for example)
2. The script will NOT download chrome , until you write in opened command line ``` chrome ``` or ``` edge ``` or ``` firefox ```, so after Edge Removal, you can close this window.

**Comment by seba2282** [comment]
Thanks for informations. Best Regards
