### ISSUE TITLE
It is bug your script PowerShell?

### ISSUE THREAD

**Issue by seba2282** [ionuttbara/edge-remover#24]
After use your script PowerShell on edge to remove, i have later some block download speed to 1 or 2 MB/s at with internet 500 mb/s. Only in browsers because example steam (games)  or Rufus (iso windows)download normally. And I wonder what's going on? You or aveyo added something to scripts? 

Best Regards

**Comment by ionuttbara** [comment]
i've seen slow speed downloads when i download the chrome or firefox in command line. after not.
this not affect in general internet speed.

**Comment by seba2282** [comment]
I see and idk if it by script then after removing edge when i putted by Microsoft store Firefox too, then download inside browser made problems + i see to my motherboard windows 10/11 put some destroyed newer driver which isn't on producent site and it destroy transfer in browser too, but not example on steam or idk where more. 
But thanks for informations if you started see too problems. It is for me small good news bc i am not alone then with problems.

**Comment by seba2282** [comment]
You fixed finally scripts for edge remover?

**Comment by ionuttbara** [comment]
i didn t see the exact cause. so in insider installation it has no problems. that s why i cannot fix that for now.

**Comment by seba2282** [comment]
And seriously it too block Microsoft edge in rules for don't come with some upgrade via windows update? And which version insider you tested? Me tested on production version windows 10/11.

**Comment by seba2282** [comment]
Interesting. So idk why made to me problems. And when you make upgrade versions, it block install edge seriously? Mean by windows update that upgrades versions.
