### ISSUE TITLE
Reinstalling the edge

### ISSUE THREAD

**Issue by uncle-yi** [ionuttbara/edge-remover#25]
What should I do if I want the edge back? It seems that when I reinstall the edge, it could not be open.

**Comment by haven80** [comment]
I confirm. After using the script, it is possible to install Edge, but it doesn't start. It is possible to launch it from the installation directory that includes the version number. However, the update and Copilot do not work. A reverse script for restoration would be helpful. In fact, any reinstallation method is not successful.

**Comment by nhathoang24** [comment]
Same question!

**Comment by nhathoang24** [comment]
do you have any solution @ionuttbara

**Comment by ionuttbara** [comment]
yes. in 2 ways. from official website download EdgeSetup or search in google ``` microsoft edge msi ``` and it will go to https://www.microsoft.com/en-us/edge/business/download?form=MA13FJ.

**Comment by ionuttbara** [comment]
i will add in next version a script which downloads msi file of edge and installs automaticly.
